apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: danasca/hive-metastore
          imagePullPolicy: Always
          volumeMounts:
            - name: metastore-site
              mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: core-site
              mountPath: /opt/hadoop-3.3.2/etc/hadoop/core-site.xml
              subPath: core-site.xml
          command: ["/opt/apache-hive-metastore-3.0.0-bin/bin/start-metastore"]
          args: ["-p", "9083"]
          ports:
            - containerPort: 9083
      volumes:
        - name: metastore-site
          configMap:
            name: metastore-site-config
        - name: core-site
          configMap:
            name: metastore-core-config



