apiVersion: v1
kind: Secret
metadata:
  name: metastore-core-config
  labels: 
    app: hive-metastore
type: Opaque
stringData:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
            <name>fs.defaultFS</name>
            <value>s3a://minio.minio:80</value>
        </property>

        <!-- Minio properties -->
        <property>
            <name>fs.s3a.connection.ssl.enabled</name>
            <value>false</value>
        </property>

        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://minio.minio:80</value>
        </property>

        <property>
            <name>fs.s3a.access.key</name>
            <value>minio123</value>
        </property>

        <property>
            <name>fs.s3a.secret.key</name>
            <value>minio123</value>
        </property>

        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>

        <property>
            <name>fs.s3a.impl</name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
    </configuration>