apiVersion: batch/v1
kind: Job
metadata:
  name: init-hms-db
  labels:
    app: hive-metastore
spec:
  template:
    spec:
      containers:
      - name: hive-metastore-init
        image: danasca/hive-metastore
        command: ["/opt/apache-hive-metastore-3.0.0-bin/bin/schematool", "--verbose", "--initSchema", "--dbType", "postgres"]
        volumeMounts:
          - name: metastore-site
            mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
            subPath: metastore-site.xml
      volumes:
        - name: metastore-site
          secret:
            secretName: metastore-site-config
      restartPolicy: OnFailure
  backoffLimit: 6
