apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv1
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv2
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv3
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv4
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   local:
      path: /data/
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv5
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv6
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv7
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv8
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv9
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv10
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv11
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv12
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv13
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv14
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv15
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv16
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv17
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv18
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv19
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv20
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv21
spec:
   capacity:
      storage: 4Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: default
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker3