apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: download-raw-weather-data-
spec:
  entrypoint: main
  # when runninng 'argo submit', these parameters can be overridden
  # -p start-decade=195 -p end-decade=196
  arguments:
    parameters:
      - name: start-decade
        value: 180
      - name: end-decade
        value: 182
  templates:
    - name: main
      # a maximum of 5 jobs will run concurrently
      parallelism: 5
      dag:
        tasks:
          - name: get-weather-data
            template: get-weather-data
            arguments:
              parameters:
                - name: decade
                  value: "{{item}}"
            withSequence:
              start: "{{ workflow.parameters.start-decade}}"
              end: "{{ workflow.parameters.end-decade}}"
          - name: get-station-data
            template: get-station-data

    # Downloads the given decade in a compressed folder in minio
    - name: get-weather-data
      inputs:
        parameters:
          - name: decade
      script:
        image: danasca/aws-cli
        command: [bash]
        source: |
          for num in 0 1 2 3 4 5 6 7 8 9
            do
              aws s3 cp --no-sign-request s3://noaa-ghcn-pds/csv.gz/{{inputs.parameters.decade}}${num}.csv.gz /tmp/weather-data/ 
            done
          gzip -d /tmp/weather-data/*.csv.gz
      outputs:
        artifacts:
          - name: downloaded-data
            path: /tmp/weather-data
            s3:
              key: "weather-data/{{ inputs.parameters.decade }}.tgz"

    # Downloads weather station info and country list
    - name: get-station-data
      script:
        image: danasca/aws-cli
        imagePullPolicy: Always
        command: [bash]
        source: |
          aws s3 cp --no-sign-request s3://noaa-ghcn-pds/ghcnd-stations.txt /tmp/weather-data/
          aws s3 cp --no-sign-request s3://noaa-ghcn-pds/ghcnd-countries.txt /tmp/weather-data/
      outputs:
        artifacts:
          - name: downloaded-data
            path: /tmp/weather-data
            s3:
              key: "weather-data/station-data.tgz"
